title: Shanta Huirem
remote_theme: oinam/oinam-jekyll

footer:
  custom: true

footer_custom: '© <script>document.write(new Date().getFullYear())</script>. All Rights Reserved. Shanta <a href="https://huirem.com">Huirem</a>.'

styles:
  forms: false
  syntax_highlighter: false